### PR TITLE
New SDK version

### PR DESCRIPTION
**Pull request by yurizanini**
Changed the SDK version in local.properties

### CODE REVIEW

**Review by ricardoprins — APPROVED** [review]
LGTM.

It might require testing by @pesogrone .

**Comment by pesogrone** [comment]
It did not work for me, @yurizanini , have you tried the previous PR that I did, maybe that one works for you, too, if not we can figure out a way to make it work for everyone

**Comment by pesogrone** [comment]
It is working now. I had to change my local.properties
flutter.minSdkVersion=21
flutter.targetSdkVersion=30
flutter.compileSdkVersion=30

**Review by pesogrone — APPROVED** [review]

**Review by yurizanini — COMMENTED** [review]
LGTM

**Pull request merged**
