### PR TITLE
Variables reference to .env

### PR DESCRIPTION
**Pull request by yurizanini**
I created the .env file and referenced the variables in build.gradle. We may want to change the variables to secrets. We can discuss it afterward.

### CODE REVIEW

**Review by ricardoprins — CHANGES_REQUESTED** [review]
A few changes:

- the .env file should be added to the .gitignore
- the .env file is a local file (not uploaded), so it should be removed from here

**Comment by yurizanini** [comment]
Right! I knew I forgot something.
I've removed the .env file and added it to .gitignore.

**Comment by yurizanini** [comment]
I think the tests are failing because the .env was removed. Would you like to talk about it tomorrow?

**Comment by yurizanini** [comment]
@ricardoprins since the .env was removed and added to .gitignore, I also had to remove its mention from assets in pubspec.yaml.

**Review by ricardoprins — APPROVED** [review]
LGTM

**Pull request merged**
